# Generated by Django 4.2.11 on 2024-03-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-data'], 'verbose_name': 'Formulário de cadastro', 'verbose_name_plural': 'Formulário de cadastros'},
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
